
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsjdsbxgottssqqlzfxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzamRzYnhnb3R0c3NxcWx6ZnhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1ODM3NDgsImV4cCI6MjA2MDE1OTc0OH0.3WVd3cIBxyUlJGBjCzwLs5YY14xC6ZNtMbb5zuxF0EY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);

// Custom types to help with conversion between application types and database types
export type JsonObject = { [key: string]: any };

// Helper function to convert timestamp IDs to UUIDs - REVISED for better UUID handling
export const convertToUUID = (id: string | null | undefined): string | null => {
  // If id is null or undefined, return null
  if (id === null || id === undefined) {
    return null;
  }
  
  // Clean up the ID by removing any formatting that might cause issues
  const cleanId = id.toString().trim();
  
  // Check if id is already a valid UUID
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
  if (uuidRegex.test(cleanId)) {
    console.log(`ID ${cleanId} já é um UUID válido`);
    return cleanId;
  }
  
  // If it's a numeric string, create a UUID-v4 style ID
  if (/^\d+$/.test(cleanId)) {
    console.log(`Convertendo ID numérico ${cleanId} para UUID`);
    
    // Return the ID in the format expected by Supabase, ensuring it's a proper UUID
    // Length is 36 characters total: 8-4-4-4-12
    const paddedId = cleanId.padStart(12, '0').substring(0, 12);
    return `00000000-0000-4000-a000-${paddedId}`;
  }
  
  // If it's not a valid UUID or numeric value, generate a new UUID
  console.log(`ID ${cleanId} não é válido, gerando novo UUID`);
  return crypto.randomUUID();
};

// Enable realtime changes for the actions table
(async () => {
  try {
    // Configure realtime channel
    const channel = supabase.channel('schema-db-changes')
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'actions' },
        (payload) => {
          console.log('Realtime change received:', payload);
        }
      )
      .subscribe();
      
    console.log('Realtime channel configured for actions table');
  } catch (error) {
    console.error('Error setting up realtime:', error);
  }
})();
